// This file is auto-generated by nextjs-studio.
// Do not edit manually — re-run `npx nextjs-studio --generate-types` to update.

// Branded scalar types — structurally strings/numbers but semantically distinct.
declare const __brand: unique symbol;
type Brand<T, B extends string> = T & { readonly [__brand]: B };

export type Email     = Brand<string, 'Email'>;
export type HttpUrl   = Brand<string, 'HttpUrl'>;
export type ISODate   = Brand<string, 'ISODate'>;
export type MediaPath = Brand<string, 'MediaPath'>;
export type ID        = Brand<string, 'ID'>;
export type Slug      = Brand<string, 'Slug'>;

/** Data shape for the "atividades" collection. */
export interface AtividadesEntry {
  color: string;
  icon: string;
  title: string;
  text: string;
}

/** Data shape for the "codigo-de-conduta" collection. */
export interface CodigoDeCondutaEntry {
  title: string;
  slug: string;
  updatedAt: ISODate;
}

/** Data shape for the "eventos" collection. */
export interface EventosEntry {
  title: string;
  slug: string;
  date: Date;
  status: string;
  kind: string;
  color: string;
  location: string;
  city: string;
  summary: string;
  cover: string;
  registrationUrl: HttpUrl;
  speakers: Array<"jessica-paz" | "lourdilene-souza" | "alessandra-gomes" | "ilana-ribeiro" | "gabriel-brasileiro" | "larissa-guimaraes" | "guilherme-carneiro" | "edson-pinheiro" | "gabriel-brina" | "tiago-danin" | "luiz-cortinhas" | "mario-souto" | "fernanda-rabello" | "paulo-moura" | "brenda-vilas-boas" | "thiago-kunz" | "ramon-rabello" | "felipe-araujo" | "fausto-blanco">;
  agenda: Array<{
    time: string;
    title: string;
    speaker: string;
  }>;
}

/** Data shape for the "faq" collection. */
export interface FaqEntry {
  q: string;
  a: string;
}

/** Data shape for the "numeros" collection. */
export interface NumerosEntry {
  value: string;
  label: string;
}

/** Data shape for the "parceiros" collection. */
export interface ParceirosEntry {
  name: string;
  slug: string;
  tier: string;
  logo: string;
  url: string;
  color: string;
}

/** Data shape for the "pessoas" collection. */
export interface PessoasEntry {
  name: string;
  slug: string;
  role: Array<"speaker" | "organizer">;
  title: string;
  company: string;
  color: string;
  avatar: string;
  tagline: string;
  interests: Array<"IA" | "Web" | "Cloud" | "Android" | "Flutter" | "Segurança" | "DevOps" | "Mobile" | "UX" | "Kotlin">;
  linkedin: string;
  instagram: string;
  twitter: string;
  github: string;
  website: string;
  gender: string;
}

// Augment both entry points so queryCollection() is fully typed regardless of import path.
declare module 'nextjs-studio' {
  interface CollectionTypeMap {
    "atividades": AtividadesEntry;
    "codigo-de-conduta": CodigoDeCondutaEntry;
    "eventos": EventosEntry;
    "faq": FaqEntry;
    "numeros": NumerosEntry;
    "parceiros": ParceirosEntry;
    "pessoas": PessoasEntry;
  }
}
declare module 'nextjs-studio/server' {
  interface CollectionTypeMap {
    "atividades": AtividadesEntry;
    "codigo-de-conduta": CodigoDeCondutaEntry;
    "eventos": EventosEntry;
    "faq": FaqEntry;
    "numeros": NumerosEntry;
    "parceiros": ParceirosEntry;
    "pessoas": PessoasEntry;
  }
}
